/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

/**
 *
 * @author brunoschalch
 */
public class TicTacToeGUI extends javax.swing.JFrame {

    int contador = 0;
    char[][] cuadriculaGato = new char[3][3];

    /**
     * Creates new form TicTacToeGUI
     */
    public TicTacToeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("jButton9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("jButton10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)
                                .addGap(18, 18, 18)
                                .addComponent(jButton10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (cuadriculaGato[0][0] == 'X' || cuadriculaGato[0][0] == 'O') {
            return; // Se cancela todo.
        }
        if (contador % 2 == 0) { // si contador es par
            jButton1.setText("X");
            cuadriculaGato[0][0] = 'X'; // Guardar copia en cuadricula.
        } else {
            jButton1.setText("O");
            cuadriculaGato[0][0] = 'O';
        }
        contador++;
          checarGanador();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (cuadriculaGato[1][0] == 'X' || cuadriculaGato[1][0] == 'O') {
            return; // Se cancela todo.
        }
        if (contador % 2 == 0) { // si contador es par
            jButton2.setText("X");
            cuadriculaGato[1][0] = 'X'; // Guardar copia en cuadricula.
        } else {
            jButton2.setText("O");
            cuadriculaGato[1][0] = 'O';
        }
        contador++;
          checarGanador();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (cuadriculaGato[2][0] == 'X' || cuadriculaGato[2][0] == 'O') {
            return; // Se cancela todo.
        }
        if (contador % 2 == 0) { // si contador es par
            jButton3.setText("X");
            cuadriculaGato[2][0] = 'X'; // Guardar copia en cuadricula.
        } else {
            jButton3.setText("O");
            cuadriculaGato[2][0] = 'O';
        }
        contador++;
          checarGanador();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (cuadriculaGato[0][1] == 'X' || cuadriculaGato[0][1] == 'O') {
            return; // Se cancela todo.
        }
        if (contador % 2 == 0) { // si contador es par
            jButton4.setText("X");
            cuadriculaGato[0][1] = 'X'; // Guardar copia en cuadricula.
        } else {
            jButton4.setText("O");
            cuadriculaGato[0][1] = 'O';
        }
        contador++;
          checarGanador();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (cuadriculaGato[1][1] == 'X' || cuadriculaGato[1][1] == 'O') {
            return; // Se cancela todo.
        }
        if (contador % 2 == 0) { // si contador es par
            jButton5.setText("X");
            cuadriculaGato[1][1] = 'X'; // Guardar copia en cuadricula.
        } else {
            jButton5.setText("O");
            cuadriculaGato[1][1] = 'O';
        }
        contador++;
          checarGanador();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (cuadriculaGato[2][1] == 'X' || cuadriculaGato[2][1] == 'O') {
            return; // Se cancela todo.
        }
        if (contador % 2 == 0) { // si contador es par
            jButton6.setText("X");
            cuadriculaGato[2][1] = 'X'; // Guardar copia en cuadricula.
        } else {
            jButton6.setText("O");
            cuadriculaGato[2][1] = 'O';
        }
        contador++;
          checarGanador();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (cuadriculaGato[0][2] == 'X' || cuadriculaGato[0][2] == 'O') {
            return; // Se cancela todo.
        }
        if (contador % 2 == 0) { // si contador es par
            jButton7.setText("X");
            cuadriculaGato[0][2] = 'X'; // Guardar copia en cuadricula.
        } else {
            jButton7.setText("O");
            cuadriculaGato[0][2] = 'O';
        }
        contador++;
          checarGanador();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (cuadriculaGato[1][2] == 'X' || cuadriculaGato[1][2] == 'O') {
            return; // Se cancela todo.
        }
        if (contador % 2 == 0) { // si contador es par
            jButton8.setText("X");
            cuadriculaGato[1][2] = 'X'; // Guardar copia en cuadricula.
        } else {
            jButton8.setText("O");
            cuadriculaGato[1][2] = 'O';
        }
        contador++;
          checarGanador();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (cuadriculaGato[2][2] == 'X' || cuadriculaGato[2][2] == 'O') {
            return; // Se cancela todo.
        }
        if (contador % 2 == 0) { // si contador es par
            jButton9.setText("X");
            cuadriculaGato[2][2] = 'X'; // Guardar copia en cuadricula.
        } else {
            jButton9.setText("O");
            cuadriculaGato[2][2] = 'O';
        }
        contador++;
        
        checarGanador();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        // Resetear todo.
        cuadriculaGato = new char[3][3];
        jButton1.setText(" ");
        jButton2.setText(" ");
        jButton3.setText(" ");
        jButton4.setText(" ");
        jButton5.setText(" ");
        jButton6.setText(" ");
        jButton7.setText(" ");
        jButton8.setText(" ");
        jButton9.setText(" ");
        jLabel1.setText(" ");
        contador=0;
    }//GEN-LAST:event_jButton10ActionPerformed

    private void checarGanador() {
        //Checa si X u O ganaron,
        //o si ya se acabó el juego, checa empate

        if (cuadriculaGato[0][0] == cuadriculaGato[1][0]
                && cuadriculaGato[1][0] == cuadriculaGato[2][0]) {
            // Las tres casillas arriba son iguales!
            // Pueden ser X, O o nada.
            if (cuadriculaGato[0][0] == 'X') {
                // X ganó!
                jLabel1.setText("X ganó!");
            } else if (cuadriculaGato[0][0] == 'O') {
                // O ganó!
                jLabel1.setText("O ganó!");
            }
             return;
        }

        if (cuadriculaGato[0][1] == cuadriculaGato[1][1]
                && cuadriculaGato[1][1] == cuadriculaGato[2][1]) {
            // Las tres casillas arriba son iguales!
            // Pueden ser X, O o nada.
            if (cuadriculaGato[0][1] == 'X') {
                // X ganó!
                jLabel1.setText("X ganó!");
            } else if (cuadriculaGato[0][1] == 'O') {
                // O ganó!
                jLabel1.setText("O ganó!");
            }
             return;
        }

        if (cuadriculaGato[0][2] == cuadriculaGato[1][2]
                && cuadriculaGato[1][2] == cuadriculaGato[2][2]) {
            // Las tres casillas arriba son iguales!
            // Pueden ser X, O o nada.
            if (cuadriculaGato[0][2] == 'X') {
                // X ganó!
                jLabel1.setText("X ganó!");
            } else if (cuadriculaGato[0][2] == 'O') {
                // O ganó!
                jLabel1.setText("O ganó!");
            }
             return;
        }

        if (cuadriculaGato[0][0] == cuadriculaGato[0][1]
                && cuadriculaGato[0][1] == cuadriculaGato[0][2]) {
            // Las tres casillas arriba son iguales!
            // Pueden ser X, O o nada.
            if (cuadriculaGato[0][0] == 'X') {
                // X ganó!
                jLabel1.setText("X ganó!");
            } else if (cuadriculaGato[0][0] == 'O') {
                // O ganó!
                jLabel1.setText("O ganó!");
            }
             return;
        }

        if (cuadriculaGato[1][0] == cuadriculaGato[1][1]
                && cuadriculaGato[1][1] == cuadriculaGato[1][2]) {
            // Las tres casillas arriba son iguales!
            // Pueden ser X, O o nada.
            if (cuadriculaGato[1][0] == 'X') {
                // X ganó!
                jLabel1.setText("X ganó!");
            } else if (cuadriculaGato[1][0] == 'O') {
                // O ganó!
                jLabel1.setText("O ganó!");
            }
             return;
        }

        if (cuadriculaGato[2][0] == cuadriculaGato[2][1]
                && cuadriculaGato[2][1] == cuadriculaGato[2][2]) {
            // Las tres casillas arriba son iguales!
            // Pueden ser X, O o nada.
            if (cuadriculaGato[2][0] == 'X') {
                // X ganó!
                jLabel1.setText("X ganó!");
            } else if (cuadriculaGato[2][0] == 'O') {
                // O ganó!
                jLabel1.setText("O ganó!");
            }
             return;
        }

        if (cuadriculaGato[0][0] == cuadriculaGato[1][1]
                && cuadriculaGato[1][1] == cuadriculaGato[2][2]) {
            // Las tres casillas arriba son iguales!
            // Pueden ser X, O o nada.
            if (cuadriculaGato[0][0] == 'X') {
                // X ganó!
                jLabel1.setText("X ganó!");
            } else if (cuadriculaGato[0][0] == 'O') {
                // O ganó!
                jLabel1.setText("O ganó!");
            }
             return;
        }

        if (cuadriculaGato[0][2] == cuadriculaGato[1][1]
                && cuadriculaGato[1][1] == cuadriculaGato[2][0]) {
            // Las tres casillas arriba son iguales!
            // Pueden ser X, O o nada.
            if (cuadriculaGato[0][2] == 'X') {
                // X ganó!
                jLabel1.setText("X ganó!");
            } else if (cuadriculaGato[0][2] == 'O') {
                // O ganó!
                jLabel1.setText("O ganó!");
            }
            return;
        }
        
        
        if (contador==9) {
            // Es empate!
             jLabel1.setText("Empate!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
